<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-CAKO4GA" failures="1" tests="2" name="Default test(failed)(failed)" time="0.098" errors="0" timestamp="2020-05-12T17:31:03 CEST">
  <testcase classname="testng_retry_failedCases.TestNgRetryFailedCases" name="check3" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng_retry_failedCases.TestNgRetryFailedCases.check3(TestNgRetryFailedCases.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- check3 -->
  <testcase classname="testng_retry_failedCases.TestNgRetryFailedCases" name="check2" time="0.003"/>
  <testcase classname="testng_retry_failedCases.TestNgRetryFailedCases" name="check1" time="0.0">
    <ignored/>
  </testcase> <!-- check1 -->
</testsuite> <!-- Default test(failed)(failed) -->
